version: "3.8"
services:
  container:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0

  container2:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5174:5173"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
